# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "locked-forker"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joshua Mervine"]
  s.date = "2012-04-17"
  s.description = " Utilities to lock and fork code for those that want to fork calls, but ensure that no one will run that code until the fork completes. "
  s.email = "joshua@mervine.net"
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "History.txt",
    "Manifest.txt",
    "README.txt",
    "Rakefile",
    "VERSION",
    "doc/History_txt.html",
    "doc/LockedForker.html",
    "doc/Manifest_txt.html",
    "doc/README_txt.html",
    "doc/created.rid",
    "doc/images/add.png",
    "doc/images/brick.png",
    "doc/images/brick_link.png",
    "doc/images/bug.png",
    "doc/images/bullet_black.png",
    "doc/images/bullet_toggle_minus.png",
    "doc/images/bullet_toggle_plus.png",
    "doc/images/date.png",
    "doc/images/delete.png",
    "doc/images/find.png",
    "doc/images/loadingAnimation.gif",
    "doc/images/macFFBgHack.png",
    "doc/images/package.png",
    "doc/images/page_green.png",
    "doc/images/page_white_text.png",
    "doc/images/page_white_width.png",
    "doc/images/plugin.png",
    "doc/images/ruby.png",
    "doc/images/tag_blue.png",
    "doc/images/tag_green.png",
    "doc/images/transparent.png",
    "doc/images/wrench.png",
    "doc/images/wrench_orange.png",
    "doc/images/zoom.png",
    "doc/index.html",
    "doc/js/darkfish.js",
    "doc/js/jquery.js",
    "doc/js/navigation.js",
    "doc/js/search.js",
    "doc/js/search_index.js",
    "doc/js/searcher.js",
    "doc/rdoc.css",
    "doc/table_of_contents.html",
    "lib/locked-forker.rb",
    "spec/locked_forker_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/jmervine/locked-forker"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.21"
  s.summary = "Locks and forks your code."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

